services:
  - type: web
    name: fifa-wc-2026-predictor
    runtime: docker
    plan: starter
    healthCheckPath: /api/status
    autoDeploy: true
    envVars:
      - key: PUBLIC_MODE
        value: "1"
