/**
 * World Cup 2026 prediction web app.
 *
 * Node serves the UI + JSON API; the Python engine (live_engine.py) stays
 * the brain. Engine artifacts live in outputs/api/*.json; stale or missing
 * artifacts are regenerated by spawning the venv Python, one job at a time.
 */

const express = require('express');
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PYTHON = path.join(ROOT, '.venv', 'bin', 'python');
const ENGINE = path.join(ROOT, 'live_engine.py');
const API_DIR = path.join(ROOT, 'outputs', 'api');

const PORT = process.env.PORT || 3000;
const CORE_TTL_MS = 15 * 60 * 1000;
const DAY_TTL_MS = 10 * 60 * 1000;

const app = express();
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// ---- public-mode guard (PUBLIC_MODE=1 on the host) -------------------------
// Engine actions are real CPU: rate-limit strangers and cap simulation depth
// so one visitor can't pin the box. Local use (no env var) is unthrottled.
const PUBLIC_MODE = process.env.PUBLIC_MODE === '1';
const ACTION_COOLDOWN_MS = 90 * 1000;
const PUBLIC_MAX_SIMS = 100000;
const lastActionAt = new Map(); // ip -> timestamp

if (PUBLIC_MODE) app.set('trust proxy', 1); // Render sits behind a proxy

function throttled(req, res) {
  if (!PUBLIC_MODE) return false;
  const now = Date.now();
  if (lastActionAt.size > 5000) lastActionAt.clear(); // crude memory bound
  const last = lastActionAt.get(req.ip) || 0;
  if (now - last < ACTION_COOLDOWN_MS) {
    res.status(429).json({
      error: `public demo: one engine action per ${ACTION_COOLDOWN_MS / 1000}s — try again shortly`,
    });
    return true;
  }
  lastActionAt.set(req.ip, now);
  return false;
}

function validTeams() {
  try {
    const core = JSON.parse(fs.readFileSync(path.join(API_DIR, 'core.json')));
    return new Set(Object.values(core.groups).flat());
  } catch {
    return new Set();
  }
}

// ---- engine job queue (one Python process at a time) ----------------------
let queue = Promise.resolve();
let currentJob = null;
const lastJobs = [];

function runEngine(args, label) {
  const job = queue.then(
    () =>
      new Promise((resolve) => {
        currentJob = { label, started: new Date().toISOString() };
        const proc = spawn(PYTHON, [ENGINE, ...args], { cwd: ROOT });
        let out = '';
        proc.stdout.on('data', (d) => (out += d));
        proc.stderr.on('data', (d) => (out += d));
        proc.on('close', (code) => {
          lastJobs.unshift({
            label,
            code,
            finished: new Date().toISOString(),
            tail: out.split('\n').filter(Boolean).slice(-8),
          });
          lastJobs.splice(10);
          currentJob = null;
          resolve(code);
        });
      })
  );
  queue = job.catch(() => {});
  return job;
}

function freshness(file) {
  try {
    const st = fs.statSync(file);
    return Date.now() - st.mtimeMs;
  } catch {
    return Infinity;
  }
}

async function ensureCore() {
  const file = path.join(API_DIR, 'core.json');
  if (freshness(file) > CORE_TTL_MS) await runEngine(['export'], 'export core');
  return file;
}

async function ensureDay(date) {
  const file = path.join(API_DIR, `day_${date}.json`);
  if (freshness(file) > DAY_TTL_MS) await runEngine(['exportday', date], `export ${date}`);
  return file;
}

function sendJson(res, file) {
  if (!fs.existsSync(file)) return res.status(404).json({ error: 'not generated yet' });
  res.type('application/json').send(fs.readFileSync(file));
}

// ---- API -------------------------------------------------------------------
app.get('/api/core', async (_req, res) => sendJson(res, await ensureCore()));

app.get('/api/day/:date', async (req, res) => {
  const date = req.params.date;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    return res.status(400).json({ error: 'date must be YYYY-MM-DD' });
  }
  sendJson(res, await ensureDay(date));
});

function actionSteps(action, query) {
  if (action === 'refresh') return [['refresh'], ['export']];
  if (action === 'news') return [['news'], ['export']];
  if (action === 'odds') {
    let n = parseInt(query.n, 10);
    if (!Number.isFinite(n)) n = 20000;
    n = Math.max(1000, Math.min(n, PUBLIC_MODE ? PUBLIC_MAX_SIMS : 1000000));
    return [['odds', String(n)], ['export']];
  }
  return null;
}

app.post('/api/run/:action', async (req, res) => {
  const steps = actionSteps(req.params.action, req.query);
  if (!steps) return res.status(400).json({ error: 'unknown action' });
  if (currentJob) return res.status(409).json({ error: 'engine busy', job: currentJob });
  if (throttled(req, res)) return;
  res.json({ started: req.params.action });
  for (const args of steps) await runEngine(args, `${req.params.action}: ${args.join(' ')}`);
  // invalidate today's map after new data
  const today = new Date().toISOString().slice(0, 10);
  const dayFile = path.join(API_DIR, `day_${today}.json`);
  if (fs.existsSync(dayFile)) fs.unlinkSync(dayFile);
});

// On-demand analysis of any pairing (the Match lab). Waits for the engine
// and returns the fresh payload — this is a real computation, not a cache.
app.post('/api/analyze', async (req, res) => {
  const { home, away, freshNews } = req.body || {};
  const teams = validTeams();
  if (!teams.has(home) || !teams.has(away) || home === away) {
    return res.status(400).json({ error: 'pick two distinct valid teams' });
  }
  if (throttled(req, res)) return;
  const args = ['analyze', home, away, ...(freshNews ? ['fresh'] : [])];
  const code = await runEngine(args, `analyze ${home} vs ${away}${freshNews ? ' +news' : ''}`);
  if (code !== 0) return res.status(500).json({ error: 'engine failed', code });
  sendJson(res, path.join(API_DIR, 'analysis_latest.json'));
});

// Triggered media search scoped to one team: force-fetches all feeds NOW.
app.post('/api/news-team', async (req, res) => {
  const { team } = req.body || {};
  if (!validTeams().has(team)) return res.status(400).json({ error: 'unknown team' });
  if (throttled(req, res)) return;
  const code = await runEngine(['newsteam', team], `news search: ${team}`);
  if (code !== 0) return res.status(500).json({ error: 'engine failed', code });
  sendJson(res, path.join(API_DIR, 'team_news_latest.json'));
});

app.get('/api/status', (_req, res) => {
  res.json({
    engine: fs.existsSync(PYTHON) ? 'ok' : 'missing venv',
    running: currentJob,
    recentJobs: lastJobs,
    coreAgeSec: Math.round(freshness(path.join(API_DIR, 'core.json')) / 1000),
  });
});

app.listen(PORT, () => {
  console.log(`WC2026 predictor running at http://localhost:${PORT}`);
});
